name: "Yedekleme Islemi"

on:
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Yedekleme [${{ github.event_name }}] #${{ github.run_number }}: ${{ github.sha }} by ${{ github.actor }}"
        uses: mhakanterzi/marketplace-test-workflow@latest
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_password: ${{ secrets.ENCRYPTION_PASSWORD }}
