name: Restore Repository
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      otp_code:
        description: 'OTP CODE - Use it as blank for first run. Get OTP code via email and run again with OTP code. OTP code expires after 90 seconds'
        required: false
      file_version_id:
        description: 'The version id of the file you want to restore. You can enter it in the first or second run while using the workflow. The version id you last entered is always kept and restored when the OTP code arrives.'
        required: false

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: "Restore Repository [${{ github.event_name }}] #${{ github.run_number }}: ${{ github.sha }} by ${{ github.actor }}"
        uses: mhakanterzi/marketplace-test-workflow-restore@latest
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_password: ${{ secrets.ENCRYPTION_PASSWORD }}
          otp_code: ${{ github.event.inputs.OTP_CODE }}
          file_version_id: ${{ github.event.inputs.FILE_VERSION_ID }}
